/*examples of order contains*/
INSERT INTO ORDERS_CONTAINS (ID_ORDERS, ID_PIZZA) VALUES (1,2);
INSERT INTO ORDERS_CONTAINS (ID_ORDERS, ID_PIZZA) VALUES (1,2);
INSERT INTO ORDERS_CONTAINS (ID_ORDERS, ID_PIZZA) VALUES (1,3);
INSERT INTO ORDERS_CONTAINS (ID_ORDERS, ID_PIZZA) VALUES (2,1);
INSERT INTO ORDERS_CONTAINS (ID_ORDERS, ID_PIZZA) VALUES (2,3);