# OLD VERSION


# INSERT INTO USERS (ROLE, LOGIN, PASSWORD) VALUES ('ADMIN', 'LEVAN', 123);
# INSERT INTO USERS(ROLE, LOGIN, PASSWORD) VALUES ('ADMIN', 'ALEKSEY', 231);
# INSERT INTO USERS(ROLE, LOGIN, PASSWORD) VALUES ('GUEST', 'ANDREY', 132);
#
# INSERT INTO PIZZA (PIZZA_NAME, PIZZA_PRICE) VALUES ('ITALIAN', 150);
# INSERT INTO PIZZA (PIZZA_NAME, PIZZA_PRICE) VALUES ('SOUTH_AFRICAN', 130);
#
# INSERT INTO COMPONENTS (COMPONENT_NAME, WEIGHT, PRICE) VALUES ('CHEESE', 100, 15);
# INSERT INTO COMPONENTS(COMPONENT_NAME, WEIGHT, PRICE) VALUES ('SOSSIGE', 100, 20);
# INSERT INTO COMPONENTS(COMPONENT_NAME, WEIGHT, PRICE) VALUES ('TOMATO_PASTE', 50, 10);
# INSERT INTO COMPONENTS(COMPONENT_NAME, WEIGHT, PRICE) VALUES ('SALAMI', 100, 25);
# INSERT INTO COMPONENTS(COMPONENT_NAME, WEIGHT, PRICE) VALUES ('CHICKEN', 100, 25);
#
# INSERT INTO COMPONENTS_BASE (COMPONENT_NAME, WEIGHT) VALUES ('CHEESE', 10000);
# INSERT INTO COMPONENTS_BASE (COMPONENT_NAME, WEIGHT) VALUES ('BAZELIC', 1000);
# INSERT INTO COMPONENTS_BASE (COMPONENT_NAME, WEIGHT) VALUES ('TOMATO_PASTE', 3000);
# INSERT INTO COMPONENTS_BASE (COMPONENT_NAME, WEIGHT) VALUES ('SALAMI', 2000);