INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("МУКА ПШЕНИЧНАЯ", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("ДРОЖЖИ", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("МАСЛО РОСТИТЕЛЬНОЕ", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("СОЛЬ", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("ВОДА", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("ЧЕСНОК", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("ТОМАТ В С/СОКУ", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("БАЗИЛИКИ ОРЕГАНО", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("СПЕЦИИ ПЕР ЧЕР", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("КУРИНОЕ ФИЛЕ", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("МАСЛО ОЛИВКОВОЕ", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("СЫР МАЦЕРЕЛЛА", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("ПОМИДОРЫ", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("БЕКОН", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("КОЛБАСА САЛЯМИ ПИКАНТЕ", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("ВЕТЧЕНА", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("ШАМПИНЬОНЫ", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("АНАНАС", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("КОЛБАСА ДОМАШНЯЯ", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("ЗЕЛЕНЬ", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("СЛИВКИ 36%", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("СЫР ДОР БЛЮ", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("СЫР РАДОМЕР", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("СЫР ПАРМЕЗАН", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("ПЕРЕЦ ЧИЛИ", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("ОХОТНЕЧЬИ КОЛБАСКИ", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("КОЛБАСА С.К", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("КУКУРУЗА (ПЕРЕЦ БОЛГАРСКИЙ)", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("МИДИИ", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("КАЛЬМАРЫ С/М", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("КРЕВЕТКИ", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("МАСЛИНЫ", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("ТУНЕЦ", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("ЛУК РЕПЧАТЫЙ", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("БАЗЕЛИК", 0, 0);
INSERT INTO components (COMPONENT_NAME, WEIGHT, PRICE) VALUE ("", 0, 0);
